config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  resources :gosts, only: :index
  resources :specials, only: :index
  resources :pages, only: :show
  resources :feedback, only: :create
  with_options only: :index do
    resources :prices
    resources :faq
    resources :contacts
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard
    else
      can :read, :all
    end
  end
end

app/models/gost.rb
class Gost < ActiveRecord::Base

  validates :file, presence: true
  validates :gost_group_id, presence: true
  belongs_to :gost_group
  mount_uploader :file, DocumentUploader

  def filename
    file.path.split('/').last.split('.')[0...-1].join
  end

end

app/models/gost_group.rb
class GostGroup < ActiveRecord::Base
  
  validates :name, presence: true
  has_many :gosts, dependent: :destroy

end

app/models/page.rb
class Page < ActiveRecord::Base

  validates :title, presence: true
  validates :key, uniqueness: true, allow_blank: true

  extend FriendlyId
  friendly_id :title, use: [:history, :finders]
  
  scope :with_key, -> { where.not(key: nil) }
  scope :published, -> { where(public: true) }

  has_many :prices

end

app/models/price.rb
class Price < ActiveRecord::Base

  validates :file, presence: true
  mount_uploader :file, DocumentUploader
  belongs_to :page
  scope :unassigned, -> { where(page_id: nil) }

  def filename
    file.path.split('/').last
  end

end

app/models/role.rb
class Role < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :users

end

app/models/setting.rb
class Setting < ActiveRecord::Base

  validates :key, presence: true, uniqueness: true

end

app/models/staff.rb
class Staff < ActiveRecord::Base

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :staff_group_id, presence: true

  belongs_to :staff_group

end

app/models/staff_group.rb
class StaffGroup < ActiveRecord::Base

  validates :name, presence: true
  has_many :staffs, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def has_roles?(role)
    if role.is_a? Symbol
      !!self.roles.where(name: role.to_s.downcase).try(:first)
    elsif Array
      role.each do |r|
        return(true) if !!self.roles.where(name: r.to_s.downcase).try(:first)
      end
      false
    end
  end

  def has_role?(role)
    !!self.roles.where(name: role.to_s.downcase).try(:first)
  end

end

app/controllers/faq_controller.rb
class FaqController < PagesController

  PAGE_KEY='faq'
  load_and_authorize_resource class: 'FrequentlyAskedQuestion'

  def index
    @frequently_asked_questions = FrequentlyAskedQuestion.all
  end

end

app/controllers/gosts_controller.rb
class GostsController < PagesController

  PAGE_KEY='gost'

  def index
    @gost_groups = GostGroup.includes(:gosts).all
  end

end

app/controllers/main_controller.rb
class MainController < PagesController
  
  PAGE_KEY = 'main'
  
  def index; end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_menu_item(menu_item, link='#', options={})
    parameters = if link == request.path
      { class: 'active' }
    else
      {}
    end
    content_tag :li, parameters do
      main_menu_link(menu_item, link, options[:icon])
    end
  end

  def main_menu_link(menu_item, link, icon_class=nil)
    link_to link do
      i = icon_class ? icon(icon_class) : nil
      "<span>#{ i }#{ menu_item[:title] }</span>".html_safe
    end
  end

  def icon(icon_class='')
    content_tag(:i, nil, class: icon_class)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gosts_helper.rb
module GostsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]> <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if !IE] -->
<html lang="en">
  <!-- <![endif] -->
  <head>
    <title>Okamagroup</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!--[if IE]> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <![endif]-->
    <link href="<%= asset_path('meta_icons/favicon.ico')%>" rel="shortcut icon" type="image/x-icon">
    <link href="<%= asset_path('meta_icons/apple-touch-icon.png')%>" rel="apple-touch-icon-precomposed">
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class="">
    <div id="wrapper">
      <header id="header">
        <div class="container">
          <nav class="navbar navbar-collapsed-sm navbar-default" id="nav" role="navigation">
            <div class="navbar-header">
              <button class="navbar-toggle" data-target=".navbar-header-collapse" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to root_path, class: 'navbar-brand' do %>
                <img alt="Jednotka" width="355" height="75" src="<%= asset_path('logo.png') %>" />
              <% end %>
            </div>
            <div class="collapse navbar-collapse navbar-header-collapse">
              <%= render 'shared/main_menu'%>
            </div>
          </nav>
        </div>
      </header>
      <div id="main" role="main">
        <%= yield %>
        <div class="fade" id="scroll-to-top">
          <i class="fa fa-chevron-up"></i>
        </div>
      </div>
      <footer id="footer">
        <div id="footer-main">
          <div class="container">
            <div class="row">
              <div class="col-md-3 col-sm-6 info-box">
                <div class="logo-container">
                  <img alt="Jednotka" width="185" height="39" src="<%= asset_path('small_logo.png') %>" />
                </div>
                <p class="no-mg-b">
                  <%= @settings[:annotation] %>
                </p>
              </div>
              <div class="col-md-6 col-sm-6 info-box">
              </div>
              <div class="col-md-3 col-sm-6 info-box">
                <h2 class="title">Контакты</h2>
                <div class="icon-boxes">
                  <div class="icon-box">
                    <div class="icon icon-wrap">
                      <i class="fa fa-icon-map-marker"></i>
                    </div>
                    <div class="content">
                      <%==@settings[:location] %>
                    </div>
                  </div>
                  <div class="icon-box">
                    <div class="icon icon-wrap">
                      <i class="fa fa-icon-phone"></i>
                    </div>
                    <div class="content">
                      <a href="tel:<%= @settings[:phone] %>"><%== @settings[:phone] %></a>
                    </div>
                  </div>
                  <div class="icon-box">
                    <div class="icon icon-wrap">
                      <i class="fa fa-icon-envelope"></i>
                    </div>
                    <div class="content"><%= link_to @settings[:email], "mailto:#{ @settings[:email] }" %></div>
                  </div>
                  <div class="icon-box">
                    <div class="icon icon-wrap">
                      <i class="fa fa-icon-globe"></i>
                    </div>
                    <div class="content"><%= link_to "www.#{ @settings[:website] }", "http://#{ @settings[:website] }"%></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="footer-copyright">
          <div class="container">
            <div class="row">
              <div class="col-lg-12 clearfix">
                <p class="copyright">
                  Copyright
                  &copy;
                  2015 Okamagroup
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <%= render partial: '/shared/yandex_metrika' %>
  </body>
</html>

app/views/pages/show.html.haml
#main-content
  .container
    .row
      .col-sm-12
        .page-header.page-header-with-icon.no-mg-t
          %i.fa-icon-tag
          %h2
            = @page.title
        .row
          .col-sm-12
            != @page.body
  = render partial: '/prices/list', locals: { prices: @page.prices }

app/views/shared/_main_menu.html.haml
%ul.nav.navbar-nav.navbar-right
  = main_menu_item @main_menu_items[:main], root_path
  = main_menu_item @main_menu_items[:services], page_path(Page.find(@main_menu_items[:services][:id]))
  = main_menu_item @main_menu_items[:prices], prices_path
  = main_menu_item @main_menu_items[:manufacture], page_path(Page.find(@main_menu_items[:manufacture][:id]))
  = main_menu_item @main_menu_items[:gost], gosts_path
  = main_menu_item @main_menu_items[:faq], faq_index_path
  = main_menu_item @main_menu_items[:contacts], contacts_path
  = main_menu_item @main_menu_items[:specials], specials_path