config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  resources :gosts, only: :index
  resources :specials, only: :index
  resources :pages, only: :show
  resources :feedback, only: :create
  with_options only: :index do
    resources :prices
    resources :faq
    resources :contacts
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard
    else
      can :read, :all
    end
  end
end

app/models/gost.rb
class Gost < ActiveRecord::Base

  validates :file, presence: true
  validates :gost_group_id, presence: true
  belongs_to :gost_group
  mount_uploader :file, DocumentUploader

  def filename
    file.path.split('/').last.split('.')[0...-1].join
  end

end

app/models/gost_group.rb
class GostGroup < ActiveRecord::Base
  
  validates :name, presence: true
  has_many :gosts, dependent: :destroy

end

app/models/page.rb
class Page < ActiveRecord::Base

  validates :title, presence: true
  validates :key, uniqueness: true, allow_blank: true

  extend FriendlyId
  friendly_id :title, use: [:history, :finders]
  
  scope :with_key, -> { where.not(key: nil) }
  scope :published, -> { where(public: true) }

  has_many :prices

end

app/models/price.rb
class Price < ActiveRecord::Base

  validates :file, presence: true
  mount_uploader :file, DocumentUploader
  belongs_to :page
  scope :unassigned, -> { where(page_id: nil) }

  def filename
    file.path.split('/').last
  end

end

app/models/role.rb
class Role < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :users

end

app/models/setting.rb
class Setting < ActiveRecord::Base

  validates :key, presence: true, uniqueness: true

end

app/models/staff.rb
class Staff < ActiveRecord::Base

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :staff_group_id, presence: true

  belongs_to :staff_group

end

app/models/staff_group.rb
class StaffGroup < ActiveRecord::Base

  validates :name, presence: true
  has_many :staffs, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def has_roles?(role)
    if role.is_a? Symbol
      !!self.roles.where(name: role.to_s.downcase).try(:first)
    elsif Array
      role.each do |r|
        return(true) if !!self.roles.where(name: r.to_s.downcase).try(:first)
      end
      false
    end
  end

  def has_role?(role)
    !!self.roles.where(name: role.to_s.downcase).try(:first)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < PagesController
  
  PAGE_KEY='contacts'

  def index
    @staff_groups = StaffGroup.includes(:staffs).all
  end

end

app/controllers/faq_controller.rb
class FaqController < PagesController

  PAGE_KEY='faq'
  load_and_authorize_resource class: 'FrequentlyAskedQuestion'

  def index
    @frequently_asked_questions = FrequentlyAskedQuestion.all
  end

end

app/controllers/gosts_controller.rb
class GostsController < PagesController

  PAGE_KEY='gost'

  def index
    @gost_groups = GostGroup.includes(:gosts).all
  end

end

app/controllers/main_controller.rb
class MainController < PagesController
  
  PAGE_KEY = 'main'
  
  def index; end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  load_and_authorize_resource class: 'Page'
  before_action :find_page, only: :index

  def show; end

  private

    def find_page
      @page = Page.includes(:prices).find_by(key: self.class::PAGE_KEY)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_menu_item(menu_item, link='#', options={})
    parameters = if link == request.path
      { class: 'active' }
    else
      {}
    end
    content_tag :li, parameters do
      main_menu_link(menu_item, link, options[:icon])
    end
  end

  def main_menu_link(menu_item, link, icon_class=nil)
    link_to link do
      i = icon_class ? icon(icon_class) : nil
      "<span>#{ i }#{ menu_item[:title] }</span>".html_safe
    end
  end

  def icon(icon_class='')
    content_tag(:i, nil, class: icon_class)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gosts_helper.rb
module GostsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/contacts/index.html.erb
<div id='main-content'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-12'>
        <p class='lead text-center no-mg-b'>
          <%== @page.body %>
        </p>
      </div>
    </div>
    <div class='row'>
        <% @staff_groups.each do |group| %>
        <div class='col-sm-12'>
          <div class='page-header page-header-with-icon'>
            <i class='fa-icon-info-sign'></i>
            <h2>
              <%= group.name %>
            </h2>
          </div>
          <% group.staffs.each do |employee| %>
            <div class='row text-center' style='margin: 0px 0px 20px 0px;'>
              <div class='col-sm-4'>
                <div class='icon-wrap icon-circle contrast-bg icon-md'>
                  <i class='fa-icon-user text-white'></i>
                </div>
                <h3>ФИО</h3>
                <ul class='list-unstyled'>
                  <li><%= employee.name %></li>
                </ul>
              </div>
              <div class='col-sm-4'>
                <div class='icon-wrap icon-circle contrast-bg icon-md'>
                  <i class='fa-icon-phone text-white'></i>
                </div>
                <h3>Телефон</h3>
                <ul class='list-unstyled'>
                  <li><%= employee.phone %></li>
                </ul>
              </div>
              <div class='col-sm-4'>
                <div class='icon-wrap icon-circle contrast-bg icon-md'>
                  <i class='fa-icon-envelope-alt text-white'></i>
                </div>
                <h3>E-Mail</h3>
                <ul class='list-unstyled'>
                  <li><%= employee.email %></li>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2'>
        <div class='page-header page-header-with-icon'>
          <i class='fa-icon-envelope-alt'></i>
          <h2>Отправка сообщения</h2>
        </div>
        <%= form_for :feedback, url: feedback_index_path, method: :post do |f| %>
        <form action='http://jednotka.bublinastudio.com/contact.html' class='form form-validation' method='get'>
          <div class='row'>
            <div class='col-sm-6'>
              <div class='form-group control-group'>
                <%= f.text_field :name, class: 'form-control', :'data-rule-required' => 'true', id: 'contact_name', placeholder: 'Имя' %>
              </div>
            </div>
            <div class='col-sm-6'>
              <div class='form-group control-group'>
                <%= f.text_field :email, class: 'form-control', :'data-rule-required' => 'true', :'data-rule-email' => 'true', id: 'contact_email', placeholder: 'E-Mail' %>
              </div>
            </div>
          </div>
          <div class='row'>
            <div class='col-sm-12'>
              <div class='form-group control-group'>
                <%= f.text_area :body, class: 'form-control', :'data-rule-required' => 'true', id: 'contact_message', placeholder: 'Ваше сообщение...'%>
              </div>
            </div>
          </div>
          <div class='row'>
            <div class='col-sm-12'>
              <button class='btn btn-contrast btn-block' type='submit'>
                Отправить
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='page-header page-header-with-icon'>
          <i class='fa-icon-map-marker'></i>
          <h2>
            Схема проезда
          </h2>
        </div>
        <div class='map-container'>
          <div id='map-canvas'></div>
        </div>
      </div>
    </div>
  </div>
  <% unless @page.prices.empty?%>
    <br />
    <br />
    <br />
    <p><%= render partial: '/prices/list', locals: { prices: @page.prices } %></p>
  <% end %>
</div>
<div class='fade' id='scroll-to-top'>
  <i class='fa-icon-chevron-up'></i>
</div>
<script src="http://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
<script>
  var initializeMap;
  
  initializeMap = function() {
    var iw1, latlng, map, marker, options;
  
    latlng = new google.maps.LatLng(<%= @settings[:lat_lng] %>);
    options = {
      scrollwheel: false,
      zoom: 16,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      mapTypeControl: true
    };
  
    map = new google.maps.Map(document.getElementById("map-canvas"), options);
  
    marker = new google.maps.Marker({
      position: latlng,
      map: map
    });
  
    iw1 = new google.maps.InfoWindow({
      content: "Мы здесь!"
    });
  
    return google.maps.event.addListener(marker, "click", function(e) {
      return iw1.open(map, this);
    });
  };
  
  google.maps.event.addDomListener(window, 'load', initializeMap);
</script>